# Generated by Django 3.1.7 on 2021-05-31 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210531_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.AddField(
            model_name='card',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
        migrations.AlterField(
            model_name='card',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game'),
        ),
    ]
