# Generated by Django 3.1.7 on 2021-06-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='password'),
        ),
    ]
