# Generated by Django 3.1.7 on 2021-06-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_game_host_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='card',
            name='special',
        ),
    ]
