# Generated by Django 3.1.7 on 2021-06-17 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_card_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='player',
        ),
    ]
