# Generated by Django 3.1.7 on 2021-06-19 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_card_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='game',
        ),
    ]
