# Generated by Django 3.1.7 on 2021-06-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_card_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
