# Generated by Django 3.1.7 on 2021-07-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='host_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='winner',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
