# Generated by Django 3.1.7 on 2021-07-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210706_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='word',
            name='winner',
        ),
    ]
